#!/usr/bin/env bash
# Bash script show subdomain info
function input_without_subdomain {
    sub_names=("www" "lb-01" "web-01" "web-02")
    for i in "${sub_names[@]}";
    do
        dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | \
        awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$i"
    done
}

function input_with_subdomain {
     dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | \
     awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

if [ $# -eq 1 ]
then
    input_without_subdomain "$1";
else
    input_with_subdomain "$1" "$2";
fi
