#!/usr/bin/env bash
# congigure redirect

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
CONFIG=\
"server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}"
bash -c "echo -e '$CONFIG' > /etc/nginx/sites-enabled/default"
service nginx start
