#!/usr/bin/env bash
#add custom header to identify server
ufw allow 'Nginx HTTP'
host=$(hostname)
CONFIG=\
"server {
	add_header X-Served-By $host;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	
	error_page 404 /error_404.html;

}"
bash -c "echo -e '$CONFIG' > /etc/nginx/sites-enabled/default"
service nginx start
