#!/usr/bin/env bash
#install and configure HAproxy
#load balancing
sudo apt update
sudo apt install haproxy -y 
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
CONFIG=\
"frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server 309888-web-01 54.237.79.93:80 check
    server 309888-web-02 34.207.63.6:80 check
"
bash -c "echo -e '$CONFIG' > /etc/haproxy/haproxy.cfg"
service haproxy restart
