#!/usr/bin/env bash
#install and configure HAproxy
#load balancing

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get -y install haproxy=2.8.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
touch /etc/haproxy/haproxy.cfg
CONFIG=\
"frontend http_front
    bind *:80
    mode http
    stats uri /haproxy?stats
    default_backend http_back
backend http_back
    balance roundrobin
    mode http
    server 309888-web-01 54.237.79.93:80 check
    server 309888-web-02 34.207.63.6:80 check
"
bash -c "echo -e '$CONFIG' > /etc/haproxy/haproxy.cfg"
service haproxy start
